import type { CategoryId } from "@/lib/topics/categories";
import type { Scenario } from "./types";

type Def = Omit<Scenario, "category">;

/**
 * Конфіг усіх сценаріїв. Новий тригер = новий запис тут (+ ключові слова в mock-класифікаторі),
 * без змін у компонентах.
 */
const defs: Record<CategoryId, Def> = {
  war: {
    label: "ВІЙНА",
    mechanic: "tear",
    cautionMechanic: "paint",
    asset: "map-rf",
    items: ["Злість", "Безсилля", "Втома від новин", "Страх"],
    copy: { title: "Рви.", hint: "Карта — просто папір. Рви скільки треба.", done: "Наше — повернемо. А зараз видихни." },
  },
  air_raid: {
    label: "ТРИВОГА",
    mechanic: "cut",
    cautionMechanic: "mute",
    asset: "siren-cable",
    items: ["Сирена", "Знову в коридор", "Недоспав", "Ще одна тривога"],
    copy: { title: "Тихо.", hint: "Смикни кабель — хай замовкне хоч тут.", done: "Тихо. Наскільки зараз можливо." },
  },
  bad_news: {
    label: "НОВИНИ",
    mechanic: "collapse",
    asset: "news-feed",
    items: ["ТЕРМІНОВО", "Ще гірше", "Експерти попереджають", "Що буде далі", "Важливо!!!"],
    copy: { title: "Згорни.", hint: "Стрічка нескінченна. Ти — ні. Згортай.", done: "Стрічку закрито. Новини почекають." },
  },
  fear_for_family: {
    label: "СТРАХ ЗА РІДНИХ",
    mechanic: "sort",
    asset: "orbit-thoughts",
    buckets: ["Можу зробити", "Не можу контролювати зараз"],
    items: ["Подзвонити", "А що, як…", "Написати «як ви?»", "Новини з їхнього міста", "Домовитись про зв’язок"],
    copy: { title: "Розклади.", hint: "Що з цього в твоїх руках, а що — ні.", done: "Що можна — зробиш. Решта не на тобі." },
  },
  uncertainty: {
    label: "НЕВІДОМІСТЬ",
    mechanic: "erase",
    asset: "fog",
    items: ["А що, як…", "Коли це скінчиться", "Що далі", "Невідомо"],
    copy: { title: "Туман.", hint: "Весь не розвієш. Розчисть маленький шматок попереду.", done: "Далеко не видно. Але крок уперед — видно." },
  },
  ex: {
    label: "КОЛИШНІ",
    mechanic: "crush",
    cautionMechanic: "dismiss",
    asset: "paper-silhouette",
    items: ["Старі повідомлення", "«Може, напишу»", "Спільні фото", "Той вечір"],
    copy: { title: "Зімни.", hint: "Це просто папір. Зімни й викинь за край.", done: "Минуле — за кадром." },
  },
  relationship_conflict: {
    label: "СВАРКА",
    mechanic: "untangle",
    asset: "tangled-lines",
    items: ["Факт", "Емоція", "Що хочу сказати"],
    copy: { title: "Розплутай.", hint: "Окремо: що сталося, що відчуваєш, що хочеш сказати.", done: "Тепер видно, де що." },
  },
  waiting_for_reply: {
    label: "НЕ ВІДПОВІДАЄ",
    mechanic: "swipe_away",
    asset: "phone-chat",
    items: ["Друкує…", "Онлайн", "Прочитано", "Ще раз перевірити"],
    copy: { title: "Відклади.", hint: "Свайпни телефон убік.", done: "20 хвилин не перевіряти. Серйозно." },
  },
  toxic_person: {
    label: "ТОКСИЧНА ЛЮДИНА",
    mechanic: "reduce",
    asset: "radio-noise",
    items: ["«Ти завжди…»", "«Я ж казав»", "«Ну ти й…»", "«Не роби з себе»"],
    copy: { title: "Тихіше.", hint: "Крути гучність на нуль.", done: "Чути тільки тебе." },
  },
  family_boundaries: {
    label: "РІДНІ ЛІЗУТЬ",
    mechanic: "drag_out",
    asset: "personal-circle",
    items: ["«Коли вже?»", "«Ми краще знаємо»", "«Ти мусиш»", "«А в людей…»"],
    copy: { title: "Твоє коло.", hint: "Виштовхни чужі фрази за межі кола.", done: "Всередині — тільки твоє." },
  },
  friendship: {
    label: "ДРУЗІ",
    mechanic: "sort",
    asset: "paper-notes",
    buckets: ["Поговорити", "Відпустити", "Не сьогодні"],
    items: ["Не відповідає", "Образа", "Не покликали", "Втомлює"],
    copy: { title: "Розклади.", hint: "Кожне — у свою купку.", done: "Вже не каша." },
  },
  loneliness: {
    label: "САМОТНІСТЬ",
    mechanic: "paint",
    fallback: "breathe",
    asset: "dark-space",
    items: ["музика", "друг", "прогулянка", "душ", "чай", "сон"],
    copy: { title: "Світло.", hint: "Торкайся — запалюй маленькі точки.", done: "Трохи світліше. Цього досить." },
  },
  work: {
    label: "РОБОТА",
    mechanic: "swipe_away",
    asset: "desk-tasks",
    keep: 1,
    items: ["Звіт", "Ще один мітинг", "Пошта", "Правки", "Таблиця", "«Термінове»", "Дзвінок"],
    copy: { title: "Скидай.", hint: "Зноси зайве зі столу. Залиш одну.", done: "Залишилась одна. Решта почекає." },
  },
  boss: {
    label: "НАЧАЛЬСТВО",
    mechanic: "mute",
    asset: "speech-bubbles",
    items: ["«Терміново!»", "«Чому досі не готово?»", "«Я ж просив»", "«На вчора»"],
    copy: { title: "Mute.", hint: "Вимикай звук кожній бульбашці.", done: "Тиша в чаті." },
  },
  client: {
    label: "КЛІЄНТ",
    mechanic: "drag_out",
    asset: "revision-cards",
    items: ["Ще варіант", "Поверніть як було", "А можна більший логотип", "Зробіть яскравіше", "Це ж дрібниця", "Ще одна правка"],
    copy: { title: "ПОЗА ТЗ.", hint: "Зноси правки туди, де їм місце.", done: "Поза ТЗ — окремий рахунок." },
  },
  deadline: {
    label: "ДЕДЛАЙН",
    mechanic: "reduce",
    asset: "clocks",
    keep: 1,
    items: ["До обіду", "На вчора", "До понеділка", "ASAP", "До кінця дня"],
    copy: { title: "Один.", hint: "Годинників забагато. Залиш один.", done: "Один дедлайн. Один." },
  },
  overload: {
    label: "ЗАВАЛ",
    mechanic: "swipe_away",
    asset: "task-pile",
    keep: 3,
    items: ["Листи", "Звіт", "Зателефонувати", "Пральна машина", "Документи", "Подарунок", "Лікар", "Оплатити", "Прибрати", "Відповісти всім"],
    copy: { title: "Три.", hint: "Залиш максимум три. Решту — геть.", done: "Три задачі. Не двадцять." },
  },
  procrastination: {
    label: "ВІДКЛАДАЮ",
    mechanic: "split",
    asset: "big-task",
    items: ["Ідеально", "Все й одразу", "Потім", "Не знаю з чого"],
    copy: { title: "На шматки.", hint: "Одна величезна задача — це кілька маленьких.", done: "Шматок — не гора." },
  },
  starting_problem: {
    label: "НЕ МОЖУ ПОЧАТИ",
    mechanic: "collapse",
    asset: "do-everything",
    items: ["ЗРОБИТИ ВСЕ", "Ідеально", "Одразу", "Сьогодні ж"],
    copy: { title: "2 хвилини.", hint: "Стискай «зробити все» до двох хвилин.", done: "Дві хвилини. Таймер — і поїхали." },
  },
  motivation: {
    label: "НЕМА СИЛ ХОТІТИ",
    mechanic: "reduce",
    asset: "progress-bar",
    items: ["100%", "Ідеальний план", "З понеділка", "Нове життя"],
    copy: { title: "1%.", hint: "Не сто. Один відсоток.", done: "Перший крок — це вже 1%." },
  },
  money: {
    label: "ГРОШІ",
    mechanic: "sort",
    asset: "flying-numbers",
    buckets: ["Зараз", "Потім", "Не потрібно"],
    items: ["Оренда", "Комуналка", "Кредитка", "Подарунок", "Підписки", "Ремонт"],
    copy: { title: "Розклади.", hint: "Що горить зараз, що потім, а що взагалі не треба.", done: "Не все горить одночасно." },
  },
  debt: {
    label: "БОРГ",
    mechanic: "split",
    asset: "big-number",
    items: ["Вся сума", "«Ніколи не віддам»", "Відсотки", "Сором"],
    copy: { title: "Частинами.", hint: "Велике число ділиться на маленькі.", done: "Не все одразу. Частинами." },
  },
  low_income: {
    label: "МАЛО ЗАРОБЛЯЮ",
    mechanic: "erase",
    asset: "others-numbers",
    items: ["«У когось $3000»", "Чужі зарплати", "Знайомий купив авто", "«Нормальні люди заробляють…»"],
    copy: { title: "Своє.", hint: "Стирай чужі цифри. Залиш свій наступний крок.", done: "Чужі цифри — не твоя карта." },
  },
  high_prices: {
    label: "ЦІНИ",
    mechanic: "throw_away",
    cautionMechanic: "dismiss",
    asset: "price-tags",
    items: ["Продукти", "Бензин", "Ліки", "Оренда", "Кава"],
    copy: { title: "Геть.", hint: "Відкинь те, що не треба вирішувати сьогодні.", done: "Сьогоднішнє — окремо від усього." },
  },
  purchase_frustration: {
    label: "ХОЧУ КУПИТИ",
    mechanic: "pause",
    asset: "want-tag",
    items: ["Хочу", "Зараз", "Знижка закінчується", "Останній розмір"],
    copy: { title: "Хочу.", hint: "Але не зараз.", done: "«Хочу, але не зараз» — теж рішення." },
  },
  weight: {
    label: "ВАГА",
    mechanic: "erase",
    asset: "scale-numbers",
    items: ["Цифра на вагах", "«Треба схуднути»", "Чужі коментарі", "Порівняння"],
    copy: { title: "Не цифра.", hint: "Стирай тиск. Тіло тут ні до чого.", done: "Вода, прогулянка, сон, нормальна їжа, відпочинок — обери одне." },
  },
  body_image: {
    label: "ДЗЕРКАЛО",
    mechanic: "erase",
    asset: "mirror-words",
    items: ["«Не така/не такий»", "«Треба інакше»", "«Знову не те»", "«Порівняй»"],
    copy: { title: "Стирай слова.", hint: "Стираються слова. Не ти.", done: "Дзеркало без коментарів." },
  },
  diet: {
    label: "ДІЄТА",
    mechanic: "tear",
    cautionMechanic: "erase",
    asset: "rules-paper",
    items: ["Не можна", "Заборонено", "Тільки з понеділка", "Зрив"],
    copy: { title: "Рви «не можна».", hint: "Правила — на шматки.", done: "Одна нейтральна турбота: попити води або нормально поїсти." },
  },
  low_energy: {
    label: "БАТАРЕЙКА 3%",
    mechanic: "pause",
    asset: "battery",
    items: ["Все встигнути", "Ще трохи", "Відповісти всім", "Бути в ресурсі"],
    copy: { title: "3%.", hint: "Вмикаємо режим економії.", done: "Режим економії увімкнено." },
  },
  sleep: {
    label: "СОН",
    mechanic: "mute",
    asset: "dim-tasks",
    items: ["Ще одна серія", "Робочий чат", "Завтрашні справи", "Стрічка"],
    copy: { title: "Приглуши.", hint: "Більшість справ — сірим. До ранку.", done: "Все інше — завтра." },
  },
  parental_overload: {
    label: "ДІТИ",
    mechanic: "mute",
    asset: "chaos-sounds",
    items: ["«Ма-а-ам!»", "«Тату!»", "Де шкарпетки", "«А можна…»", "Плач"],
    copy: { title: "Тихо.", hint: "Приглушуй звуки по одному.", done: "Десять секунд тиші. Твої." },
  },
  mess: {
    label: "БЕЗЛАД",
    mechanic: "reduce",
    asset: "room-items",
    keep: 5,
    items: ["Чашка", "Одяг на стільці", "Посуд", "Папери", "Коробки", "Зарядки", "Пакети", "Іграшки"],
    copy: { title: "П’ять.", hint: "Тільки п’ять речей. Решта — розмито.", done: "П’ять речей — це вже план." },
  },
  no_time_for_self: {
    label: "НЕМА ЧАСУ НА СЕБЕ",
    mechanic: "paint",
    fallback: "breathe",
    asset: "calendar",
    items: ["15 хвилин", "Чай", "Душ", "Вийти надвір"],
    copy: { title: "15 хвилин.", hint: "Виділи в календарі п’ятнадцять хвилин. Тільки свої.", done: "15 хвилин — твої. Без пояснень." },
  },
  social_media: {
    label: "СОЦМЕРЕЖІ",
    mechanic: "dismiss",
    asset: "infinite-feed",
    items: ["Рілс", "Ще один рілс", "Чужа відпустка", "Срач у коментарях", "Реклама"],
    copy: { title: "Закрий.", hint: "Свайпни стрічку геть.", done: "Стрічка закрита. Світ на місці." },
  },
  comparison: {
    label: "ПОРІВНЯННЯ",
    mechanic: "erase",
    asset: "others-profiles",
    items: ["Чужий профіль", "«А вона вже…»", "«А він вже…»", "Чуже фото"],
    copy: { title: "Своє.", hint: "Стирай чужі профілі.", done: "Залишилась твоя траєкторія." },
  },
  success_comparison: {
    label: "ЧУЖІ УСПІХИ",
    mechanic: "dismiss",
    asset: "high-rises",
    items: ["Чийсь стартап", "Чиєсь підвищення", "Чужа квартира", "«У 25 вже…»"],
    copy: { title: "Твоя дорога.", hint: "Відсунь чужі висотки.", done: "Камера — на твоїй дорозі." },
  },
  hate_job: {
    label: "НЕНАВИДЖУ РОБОТУ",
    mechanic: "pause",
    asset: "two-doors",
    items: ["Залишитись", "Піти"],
    copy: { title: "Дві двері.", hint: "Ніхто не вирішує за тебе. Просто подивись на обидві.", done: "Рішення — твоє. Не сьогодні о третій ночі." },
  },
  quit_impulse: {
    label: "ХОЧУ ЗВІЛЬНИТИСЬ",
    mechanic: "freeze",
    asset: "big-button",
    items: ["Звільнитися", "Написати заяву", "Все, досить"],
    copy: { title: "ЗВІЛЬНИТИСЬ", hint: "Тисни. А потім питання.", done: "Зараз чи після сну?" },
  },
  text_ex: {
    label: "НАПИСАТИ КОЛИШНЬОМУ",
    mechanic: "freeze",
    asset: "unsent-message",
    items: ["«Привіт, як ти?»", "«Я тут подумала…»", "«Просто цікаво»"],
    copy: { title: "Пауза.", hint: "Перед «надіслати» — заморозь.", done: "Не надіслано. Можна вирішити завтра." },
  },
  argument_impulse: {
    label: "ХОЧУ ПОСВАРИТИСЬ",
    mechanic: "throw_away",
    cautionMechanic: "dismiss",
    asset: "reply-draft",
    items: ["Моя репліка", "Ще одна", "І ще"],
    copy: { title: "Сюди.", hint: "Відправ це сюди, а не людині.", done: "Відправлено. В нікуди. Так краще." },
  },
  prove_something: {
    label: "ДОВЕСТИ",
    mechanic: "erase",
    asset: "prove-word",
    items: ["ДОВЕДИ", "Покажи їм", "Хай побачать"],
    copy: { title: "ДОВЕДИ", hint: "Стирай.", done: "А треба?" },
  },
  not_understood: {
    label: "НЕ РОЗУМІЮТЬ",
    mechanic: "swipe_away",
    asset: "chaotic-words",
    keep: 1,
    items: ["Мене не чують", "Я не про це", "Ви не так зрозуміли", "Мені важливо", "Я просто втомилась/втомився"],
    copy: { title: "Одна фраза.", hint: "Прибери зайве. Залиш те, що хочеш донести.", done: "Ось що ти хочеш донести." },
  },
  not_appreciated: {
    label: "НЕ ЦІНУЮТЬ",
    mechanic: "drag_out",
    asset: "ratings",
    items: ["«Могла б і краще»", "«Ну нормально»", "Ніхто не помітив", "«Це ж твоя робота»"],
    copy: { title: "Відсунь.", hint: "Чужі оцінки — убік.", done: "Що тобі зараз потрібно?" },
  },
  plans_failed: {
    label: "ПЛАНИ ЗЛЕТІЛИ",
    mechanic: "paint",
    asset: "broken-route",
    items: ["План А", "Як мало бути", "Все зіпсовано"],
    copy: { title: "Новий маршрут.", hint: "Старий зламався. Намалюй короткий інший.", done: "Маршрут перебудовано." },
  },
  mistake: {
    label: "ПОМИЛКА",
    mechanic: "collapse",
    asset: "mistake-word",
    items: ["ПОМИЛКА"],
    copy: { title: "ПОМИЛКА", hint: "Стискай її до розміру примітки.", done: "Примітка на полях. Не вирок." },
  },
  shame: {
    label: "СОРОМ",
    mechanic: "reduce",
    asset: "heavy-layer",
    items: ["Як я міг/могла", "Всі бачили", "Сором"],
    copy: { title: "Легше.", hint: "Повільно зменшуй цей шар.", done: "Вже не на весь екран." },
  },
  self_anger: {
    label: "ЗЛЮСЬ НА СЕБЕ",
    mechanic: "erase",
    asset: "mirror-outline",
    items: ["Ідіот(ка)", "Знову", "Нічого не можу", "Слабак"],
    copy: { title: "Стирай слова.", hint: "Слова — геть. Ти залишаєшся.", done: "Ти — не ці слова." },
  },
  numbness: {
    label: "НІЧОГО НЕ ВІДЧУВАЮ",
    mechanic: "breathe",
    asset: "clouds",
    items: [],
    copy: { title: "Можеш просто побути тут.", hint: "Нічого не треба робити.", done: "Ти тут. Цього досить." },
  },
  everything: {
    label: "ВСЕ",
    mechanic: "swipe_away",
    asset: "topic-bubbles",
    itemsFrom: "topics",
    keep: 1,
    items: ["Робота", "Гроші", "Втома", "Люди"],
    copy: { title: "По одному.", hint: "Прибери все, крім одного.", done: "Одне. З цим уже можна жити." },
  },
  unknown: {
    label: "ЩОСЬ",
    mechanic: "crush",
    cautionMechanic: "breathe",
    asset: "big-everything",
    items: ["ВСЕ", "Взагалі все", "Не знаю що"],
    copy: { title: "ВСЕ.", hint: "Тисни й тримай.", done: "Видихни. Можна не знати, що саме." },
  },
};

export const SCENARIOS: Record<CategoryId, Scenario> = Object.fromEntries(
  Object.entries(defs).map(([category, def]) => [category, { category, ...def }]),
) as Record<CategoryId, Scenario>;

export function getScenario(category: CategoryId): Scenario {
  return SCENARIOS[category];
}
